export const STARTER_HTML = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Forma — spaces for living</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#f4f1ea;color:#28372f;font-family:Arial,sans-serif}nav{display:flex;align-items:center;justify-content:space-between;padding:27px 38px;border-bottom:1px solid #dcded3}.brand{font-family:Georgia,serif;font-size:32px;letter-spacing:-2px}nav a{font-size:10px;letter-spacing:1px;text-transform:uppercase;color:inherit;text-decoration:none;margin-left:22px}.hero{padding:51px 38px 34px}.eyebrow{font-size:9px;letter-spacing:2px;text-transform:uppercase;display:flex;align-items:center;gap:9px}.eyebrow:before{content:'';width:6px;height:6px;border-radius:100%;background:#9ca87e}h1{font-family:Georgia,serif;font-weight:400;font-size:65px;line-height:1.03;letter-spacing:-3px;margin:23px 0 22px;max-width:570px}h1 em{color:#89967a;font-weight:400}.intro{display:flex;align-items:end;justify-content:space-between;gap:24px}.intro p{font-size:12px;line-height:1.7;max-width:280px;color:#738073;margin:0}.button{color:#28372f;font-size:11px;text-decoration:none;white-space:nowrap;border-bottom:1px solid #83927d;padding-bottom:8px}.scene{height:270px;position:relative;margin:0 18px;overflow:hidden;background:linear-gradient(135deg,#d7d7c6,#ede5d5 65%)}.window{position:absolute;left:39%;top:0;width:38%;height:82%;background:linear-gradient(115deg,#a3b2a1,#d0d9ba 45%,#718f71);border:13px solid #e7e1d3;border-top:0;box-shadow:20px 14px 25px #74725730}.window:after{content:'';position:absolute;top:0;left:48%;height:100%;width:7px;background:#e7e1d3}.floor{position:absolute;bottom:0;left:0;width:100%;height:22%;background:#c2b49a;transform:skewY(-5deg);transform-origin:bottom left}.sofa{position:absolute;width:49%;height:87px;bottom:29px;left:10%;background:#ddd5be;border-radius:28px 28px 10px 10px;box-shadow:0 13px 20px #635c4430;border-bottom:20px solid #c8bea4}.sofa:after{content:'';position:absolute;width:33%;height:55px;background:#9b9f7b;left:13%;top:-14px;border-radius:12px;transform:rotate(-8deg)}.table{position:absolute;width:130px;height:30px;border-radius:50%;background:#776d53;bottom:31px;right:18%;box-shadow:0 12px 0 -4px #514c3c}.plant{position:absolute;right:8%;bottom:38px;width:38px;height:65px;background:#a48d72;border-radius:3px 3px 13px 13px}.plant:before{content:'';position:absolute;width:75px;height:108px;border-radius:80% 5% 70% 10%;background:#667b54;bottom:48px;left:-30px;transform:rotate(-18deg)}.caption{display:flex;justify-content:space-between;font-size:9px;text-transform:uppercase;letter-spacing:1.5px;padding:19px 38px 27px}.footer{border-top:1px solid #dcded3;padding:23px 38px;display:flex;justify-content:space-between;font-size:10px;color:#7d8576}@media(max-width:500px){nav{padding:22px}nav a{margin-left:10px;font-size:8px}.hero{padding:40px 22px 28px}h1{font-size:51px}.intro{align-items:start;flex-direction:column;gap:20px}.scene{height:245px}.caption{padding:18px 22px;font-size:8px}.footer{padding:22px}.sofa{width:65%;left:6%}.table{right:8%}}
</style></head><body>
<nav><span class="brand">forma.</span><div><a href="#work">Our work</a><a href="#about">The studio</a><a href="mailto:hello@example.com">Get in touch ↗</a></div></nav>
<main><section class="hero"><div class="eyebrow">Independent architecture & interiors</div><h1>Good spaces.<br><em>Better living.</em></h1><div class="intro"><p>Thoughtful places for the everyday.<br>We bring warmth, purpose, and a little possibility to the spaces you call yours.</p><a class="button" href="#work">Explore our work &nbsp; ↗</a></div></section>
<section id="work" class="scene" aria-label="An abstract sunlit living room"><div class="window"></div><div class="floor"></div><div class="sofa"></div><div class="table"></div><div class="plant"></div></section>
<div class="caption"><span>01 / The slow house</span><span>Residential · 2026</span></div></main>
<footer id="about" class="footer"><span>Considered, from the ground up.</span><span>Independent by design</span></footer>
</body></html>`

export const BLANK_HTML = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Untitled website</title><style>*{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;place-content:center;text-align:center;background:#f5f3ee;color:#30362c;font-family:Arial,sans-serif}p{font-size:12px;color:#7b8077}h1{font-family:Georgia,serif;font-size:48px;font-weight:400;letter-spacing:-2px}</style></head><body><p>A LITTLE ROOM FOR AN IDEA</p><h1>Something starts here.</h1><p>Tell your agent what you have in mind.</p></body></html>`
